name: Build

on: [push, pull_request]

jobs:
  build:
    name: build
    strategy:
      matrix:
        GOOS: ['linux', 'darwin']
        GOARCH: ['amd64']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - run: |
          go env
          go build -v ./...
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
